spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DB_URL:172.119.0.3}:${DB_PORT:5434}/developedb
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
