spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop # drop удобен для теста проекта.
  datasource:
    platform: jdbc:postgresql
    url: jdbc:postgresql://localhost:5432/developedb
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
